/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScreenSharingPrefView.java
 *
 * Created on Oct 21, 2009, 11:07:12 AM
 */

package com.ben.chat.client.views;

import com.ben.chat.client.constant.ChatConstants;

/**
 *
 * @author bendaccache
 */
public class ScreenSharingPrefView extends javax.swing.JDialog {
    private boolean canceled = false;
    private ClientChatView cv;
    private String pearNickname;

    /** Creates new form ScreenSharingPrefView */
    public ScreenSharingPrefView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cv = ClientChatView.getInstance();
    }

    public boolean isCancelled() {
        return canceled;
    }

    public void setNickname(String fromNickname) {
        pearNickname = fromNickname;
    }

    public void setScreenControl(boolean b) {
        screenControlBox.setSelected(b);
    }

    public boolean isControl() {
        return screenControlBox.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        screenControlBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ben.chat.client.views.ClientChatApp.class).getContext().getResourceMap(ScreenSharingPrefView.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        screenControlBox.setText(resourceMap.getString("screenControlBox.text")); // NOI18N
        screenControlBox.setName("screenControlBox"); // NOI18N
        screenControlBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenControlBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenControlBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(screenControlBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        canceled = true;
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void screenControlBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenControlBoxActionPerformed
        if(screenControlBox.isSelected()){
            cv.sendInt(ChatConstants.SCREEN_CONTROL_REQUEST);
            cv.sendText(pearNickname);
        }else{
            cv.sendInt(ChatConstants.SCREEN_CONTROL_END);
            cv.sendText(pearNickname);
        }
}//GEN-LAST:event_screenControlBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox screenControlBox;
    // End of variables declaration//GEN-END:variables

}
