/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoggerView.java
 *
 * Created on Nov 16, 2009, 5:55:53 PM
 */
package com.ben.chat.client.views;

import com.ben.chat.client.constant.ChatConstants;
import com.ben.chat.client.views.ClientChatApp;
import com.ben.chat.client.views.ClientChatView;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author benoitdaccache
 */
public class LoggerView extends javax.swing.JFrame {

    /** Creates new form LoggerView */
    public LoggerView() {
        initComponents();
        initContent();
        this.setLocationRelativeTo(ClientChatApp.getApplication().getMainFrame());
        this.setTitle("Log");
        this.setVisible(true);
    }

    private void appendToJPanel(String string) {
        errorPane.setText(errorPane.getText() + string);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        errorPane = new javax.swing.JTextPane();
        sendButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ben.chat.client.views.ClientChatApp.class).getContext().getResourceMap(LoggerView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        errorPane.setBackground(resourceMap.getColor("errorPane.background")); // NOI18N
        errorPane.setEditable(false);
        errorPane.setFont(resourceMap.getFont("errorPane.font")); // NOI18N
        errorPane.setForeground(resourceMap.getColor("errorPane.foreground")); // NOI18N
        errorPane.setText(resourceMap.getString("errorPane.text")); // NOI18N
        errorPane.setName("errorPane"); // NOI18N
        jScrollPane1.setViewportView(errorPane);

        sendButton.setText(resourceMap.getString("sendButton.text")); // NOI18N
        sendButton.setName("sendButton"); // NOI18N
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        clearButton.setText(resourceMap.getString("clearButton.text")); // NOI18N
        clearButton.setName("clearButton"); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearButton)
                .addGap(278, 278, 278)
                .addComponent(sendButton)
                .addGap(6, 6, 6))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        if (errorPane.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "No entry in Log");
            return;
        }
        ClientChatView.getInstance().sendInt(ChatConstants.REPORT);
        ClientChatView.getInstance().sendText("Logger");
        ClientChatView.getInstance().sendText(errorPane.getText());
        JOptionPane.showMessageDialog(null, "Thank you..");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        File f = new File(ChatConstants.LOG_FILE_DIR);
        f.delete();
        errorPane.setText("");
}//GEN-LAST:event_clearButtonActionPerformed
    private void initContent() {
        try {
            BufferedReader in = null;
            File f = new File(ChatConstants.LOG_FILE_DIR);
            in = new BufferedReader(new FileReader(f));
            String line = null;
            while ((line = in.readLine()) != null) {
                appendToJPanel(line + "\n");
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No log found");
        } catch (IOException ex) {
            Logger.getLogger(LoggerView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextPane errorPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
