/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * 
 *
 * Created on Oct 17, 2009, 7:28:14 PM
 */
package com.ben.chat.client.views;

import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author bendaccache
 */
public class ScreenSharingView extends javax.swing.JFrame {
    private boolean isDisposed =false;
    private MouseEvent evt;
    private boolean mouseClicked =false;
    private MouseEvent mousePressedEvent;
    private boolean mousePressed = false;
    private MouseEvent mouseRelesedEvent;
    private boolean mouseReleased = false;


    /** Creates new form test */
    public ScreenSharingView(java.awt.Frame parent, boolean modal) {
        super("Screen sharing");
        initComponents();
        this.setLocationRelativeTo(ClientChatApp.getApplication().getMainFrame());
    }

    public double  getRelativePositionX() throws NullPointerException{
        double x = sharingDisplayLabel.getMousePosition().getX();
        int width = sharingDisplayLabel.getWidth();
        double  posrx = (double) (x / width);
        return posrx;
    }

    public double getRelativePositionY(){
        double x = sharingDisplayLabel.getMousePosition().getY();
        int width = sharingDisplayLabel.getHeight();
        double  posry = (double) (x / width);
        return posry;
    }

    public boolean isMouseCLick(){
        return mouseClicked;
    }

    public boolean isMousePressed(){
        return mousePressed;
    }

    public boolean isMouseReleased(){
        return mouseReleased;
    }

    public MouseEvent getMousePressed(){
        mousePressed =false;
        return mousePressedEvent;
    }

    public MouseEvent getMouseReleased(){
        mouseReleased = false;
        return mouseRelesedEvent;
    }

    public MouseEvent getMouseClick(){
        mouseClicked= false;
        return evt;
    }


    public boolean isDisposed() {
        return isDisposed;
    }

    public void setLabel(ImageIcon icon) {
        sharingDisplayLabel.setIcon(icon);
    }

    @Override
    public void setTitle(String username){
        super.setTitle("Screen sharing with "+username);
    }

    @Override
    public void dispose(){
        isDisposed = true;
        super.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sharingDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        sharingDisplayLabel.setName("sharingDisplayLabel"); // NOI18N
        sharingDisplayLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sharingDisplayLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sharingDisplayLabelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sharingDisplayLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sharingDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sharingDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sharingDisplayLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharingDisplayLabelMouseClicked
        this.evt = evt ;
        mouseClicked = true;
}//GEN-LAST:event_sharingDisplayLabelMouseClicked

    private void sharingDisplayLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharingDisplayLabelMousePressed
        this.mousePressedEvent = evt;
        mousePressed = true;
    }//GEN-LAST:event_sharingDisplayLabelMousePressed

    private void sharingDisplayLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharingDisplayLabelMouseReleased
        this.mouseRelesedEvent = evt;
        mouseReleased = true;
    }//GEN-LAST:event_sharingDisplayLabelMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel sharingDisplayLabel;
    // End of variables declaration//GEN-END:variables

}
