/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SendFileProgress.java
 *
 * Created on Mar 21, 2009, 6:59:33 PM
 */

package com.ben.chat.client.views;

import com.ben.chat.client.sound.SoundFile;
import com.ben.chat.client.sound.SoundModule;
import com.ben.chat.client.constant.preferences.PreferencesWrapper;
import com.ben.chat.client.openapps.OpenFile;
import java.io.File;
import javax.swing.JFrame;

/**
 *  cree une fenetre de progression pour l'envoi et la reception de fichier
 * @author bendaccache
 */
public class TranfertProgressView extends javax.swing.JFrame{
    private ClientChatView cv;
    private String title;
    private boolean notCancelled =true;
    private File file;

    /** Creates new form SendFileProgress */
    public TranfertProgressView(java.awt.Frame parent, boolean modal,String title) {
        super("Transfert");
        this.cv=ClientChatView.getInstance();
        this.title= title;
        initComponents();
        this.setTitle(title);
        this.setLocationRelativeTo(ClientChatApp.getApplication().getMainFrame());
    }

    public boolean notCancelled() {
        return notCancelled;
    }

    public void setCancelEnabled(boolean b) {
        this.cancelButton.setEnabled(b);
    }

    public void setFile(File f) {
        this.file = f;
        openFileLabel.setEnabled(true);
        openFileLabel.setText("open File");
    }

    public void setSpeed(long l) {//B/ms
        tspeed.setText(Long.toString(l)+" KB/s");
    }

    public void setTimeLeft(long time){
        int min = (int) (time / 1000 / 60);
        int sec = (int) (time - (min*60*1000))/1000;
        timeLeft.setText("time left : "+min +"m"+ sec+"s");

    }

    /** This method is called from within the constructor to
     * initialize the form.••
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        hideButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        timeLeft = new javax.swing.JLabel();
        openFileLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        tspeed = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ben.chat.client.views.ClientChatApp.class).getContext().getResourceMap(TranfertProgressView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        progressBar.setName("progressBar"); // NOI18N

        hideButton.setText(resourceMap.getString("hideButton.text")); // NOI18N
        hideButton.setName("hideButton"); // NOI18N
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setIconTextGap(7);
        jLabel1.setName("jLabel1"); // NOI18N

        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setEnabled(false);
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        timeLeft.setText(resourceMap.getString("timeLeft.text")); // NOI18N
        timeLeft.setName("timeLeft"); // NOI18N

        openFileLabel.setFont(resourceMap.getFont("openFileLabel.font")); // NOI18N
        openFileLabel.setForeground(resourceMap.getColor("openFileLabel.foreground")); // NOI18N
        openFileLabel.setText(resourceMap.getString("openFileLabel.text")); // NOI18N
        openFileLabel.setEnabled(false);
        openFileLabel.setName("openFileLabel"); // NOI18N
        openFileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openFileLabelMouseClicked(evt);
            }
        });

        speedLabel.setText(resourceMap.getString("speedLabel.text")); // NOI18N
        speedLabel.setName("speedLabel"); // NOI18N

        tspeed.setText(resourceMap.getString("tspeed.text")); // NOI18N
        tspeed.setName("tspeed"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(progressBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(openFileLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hideButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(closeButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(speedLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 142, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(tspeed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                        .add(timeLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(85, 85, 85)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(timeLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tspeed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(speedLabel))
                .add(9, 9, 9)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(closeButton)
                    .add(hideButton)
                    .add(cancelButton)
                    .add(openFileLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * met la fenetre en arriere plan
     * @param evt
     */
    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        this.toBack();
    }//GEN-LAST:event_hideButtonActionPerformed

    /**
     * ferme la fenetre
     * @param evt
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.notCancelled=false;
}//GEN-LAST:event_cancelButtonActionPerformed

    private void openFileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFileLabelMouseClicked
        OpenFile.openFile(file);
    }//GEN-LAST:event_openFileLabelMouseClicked

    /**
     * affiche sur la barre de progression la valeur
     * @param val
     */
    public void setProgressBarValue(int val){
        progressBar.setValue(val);
        speedLabel.setText(val+"%");
    }

    /**
     * active le bouton close
     */
    public void setCloseActive(){
        this.toFront();
        speedLabel.setText("Transfert complete");
        tspeed.setText("");
        hideButton.setEnabled(false);
        cancelButton.setEnabled(false);
        closeButton.setEnabled(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if(PreferencesWrapper.getPreferences().isSound())
            new SoundModule(SoundFile.END).start();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton hideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel openFileLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JLabel timeLeft;
    private javax.swing.JLabel tspeed;
    // End of variables declaration//GEN-END:variables

}
